[package]
name = "check_mailq"
version = "0.1.0"
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
edition = "2018"
description = "Nagios/Sensu check to determine the number of mails in the queue"

# As of NixOS 19.09, we need the old Cargo.lock format. Build manually with
# cargo +1.40.0 build (new Cargo.lock introduced in 1.41.0)

[profile.release]
lto = "thin"

[dependencies]
anyhow = "1"
clap = { version = "2.32", default-features = false }
regex = "1.3.7"
structopt = "0.3.14"
subprocess = "=0.2.1"
