[package]
name = "check_age"
version = "0.1.0"
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
edition = "2018"
description = "Checks for outdated files and symlinks"

[dependencies]
clap = { version = "2", features = ["wrap_help"] }
humantime = "2.0.1"
structopt = "0.3.17"
anyhow = "1.0.32"

[dev-dependencies]
tempfile = "3.1.0"
nix = "0.18.0"
