[package]
name = "check_age"
version = "0.2.0"
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
edition = "2018"
description = "Checks for outdated files and symlinks"

[dependencies]
anyhow = "1.0.32"
humantime = "2.0.1"
structopt = "0.3.17"

[dev-dependencies]
nix = "0.18.0"
tempfile = "3.1.0"
