[package]
name = "roundcube-chpasswd"
description = "Password updater for Roundcube/Dovecot"
version = "0.1.0"
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
edition = "2018"

[dependencies]
anyhow = "1"
clap = "2"
env_logger = "0.7"
fs2 = "0.4"
log = "0.4"
pwhash = "0.3"

[dev-dependencies]
regex = "1.3"
tempfile = "3"
