[package]
name = "logcheck-helper"
version = "1.0.1"
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
description = "Derive a correct regular expression for logcheck ignore patterns"
edition = "2018"

[dependencies]
colored = "2"
gumdrop = "0.8"
rustyline = "6"
regex = "1"
serde_yaml = "0.8"

[profile.release]
lto = true
